dataset: bodyfat_scale

figpath: figs
dump_path: dump

ylim: [0, 80]

shared:
  min_size_scale: 1.5
  max_size_scale: 5
  n_sizes: 10
  n_repeat: 25
  criterion: A

methods:
  greedy:
    name: "Greedy"
    target: Greedy
    params: {}

  uniform:
    name: "Uniform"
    target: Uniform
    params: {}
    

  predictive_length:
    name: "Predictive length"
    target: PredictiveLength
    params: {}

  plain_reg_dpp:
    name: "Reg DPP w/o SDP"
    target: RegDPP
    params:
      sdp: false

  reg_dpp_sdp:
    name: "Reg DPP w SDP"
    target: RegDPP
    params:
      sdp: true